### ISSUE TITLE
CL_WhisperPass

### ISSUE THREAD

**Issue by felixLumyni** [felixLumyni/battlepass#11]
*Branched from CL_Whisper-v1.2.1.pk3*

[Download v9](https://cdn.discordapp.com/attachments/1313999852195024976/1329213333907439616/CL_WhisperPass_v9.pk3?ex=678985e2&is=67883462&hm=6f3123f88fa4e39eb77f1e4082e13fb3b653dac5fee6f786e3213ce29abbf159&)

### 🌎 Global changes
- Whisper is 0,0 no matter what. Even when using shield specials that would put her into a spin state she is 0 defense. Only time when she has active stats is ONLY during hammer or invulnerability.
- Gave a name for each ability (console hit feed)
- Shields: 0
- Weight: 90
- Now depends on ammo to use most abilities (Check "Ammo system" section all the way down)

### ⚡ Laser
- Not grabbable by Silver
- Single bounce
- Levels up in priority after 0.75s
- Fixed being unblockable in the same frame it spawns
- Increased stun (0s -> 0.2s)
- Can't spawn inside of floors and walls
- Can't damage players that are air dodging

### 🚀 Rocket
- Whisper can't parry her own rockets
- Blast radius launchs in tumble instead of damaging (still parriable, also still has contact dmg)

### 🧊 Cube
- 0/0 (attack/defense), sweetspot: 2/1 (attack/defense)
 - Only has ATK while whisper is in the air
- Momentum cap on flag touch
- Players take damage if cubed for too long
- Spectators can't get cubed
- Fixed survival matches instantly ending if Whisper attempts to uncube an already cubed scaled player during overtime (???)
- Ray gets ``mo.ray_fixstuff`` when breaking out of cube (thanks, Ray)
- Players get a minimum cooldown of 3s if they are cubed during an actionstate
- Hit message tweaks
- Revived players are uncubed properly

### 🌀 Spike
- If saw is parried whisper is put in a tumble
- Slightly increased hitbox (+8FRAC in radius and in height)
- Now has a telegraphed windup
- Is smoothly cancelled by guard moves

### ☂️ Hover
- Momentum cap on flag touch
- If this cancelled the hammer ability, apply momentum cap

# AMMO SYSTEM

| Variable | Default value |
| ------------- | ------------- |
WHISPER_MAX_AMMO      | 20
WHISPER_ROCKET_COST    | 6
WHISPER_LASER_COST`      | 1
WHISPER_HAMMER_COST | 2
WHISPER_SAW_COST         | 3

| ClientVar | Default Value |
| ------------- | ------------- |
| ``whisperbattle_hud`` | 1 |

| Battle special | Cost | Cooldown | What it does |
| ------------- | ------------- | ------------- | ------------- |
| Reload | 15 Rings | 1.75 seconds | Grants max ammo. Whisper is slower and can't use abilities while reloading. Automatically used by trying to fire a laser without enough ammo, but doing so will provide only half of the usual ammo. |

**Comment by felixLumyni** [comment]
TODO: Ammo HUD (Not entirely sure what else she needs)

**Comment by lightdasher** [comment]
Replace Whisper's rockets AOE to tumble instead, direct contact of rocket does damage
Remove hammer flip tech for battlemod specifically
(Rocket jump...?)

**Comment by felixLumyni** [comment]
- [x] Remove maxammo and ammo cost commands
- [x] Lower actioncost (20 -> 15)
- [x] Lower max 🧊 Cube time (3s -> 2s)
- [x] Raised 🧊 Cube sweetspot defense (0 -> 1)
- [x] Fixed a bug where whisperswap sometimes caused spin abilities to not be used

### LD's bug list
- [x] Fix teammates being able to parry 🌀 Spike
- [x] Fix teammates being able to block ⚡ Laser
- [x] Fix spectators being able to be 🧊 Cube'd
- [x] Fix enemies being able to air dodge out of 🧊 Cube instantly
- [x] Fix 🧊 Cube not awarding hit/kill credit to Whisper
- [x] Fix 🚀Rocket tumble not awarding kill credit to Whisper

### Strangest bugs ever (Ty Cap, and Meh) - Will be fixed when whisperpass.pk3 is out
- [x] Fix being able to cheese 🚀 Rocket's ammo cost by firing in the same frame it gets available
- [x] Fix 🧊 Hammer and 🌀 Saw only having cost for one player (??) (Happens almost every match)
- [x] Fix ⚡ Laser and 🚀 using ammo but not firing (??)

### Meh's suggestions
- [x] Fix ☂️ Hover carry

### CK's suggestions
- [x] Clearer audio/visual cues for attempting to fire without ammo

**Comment by lightdasher** [comment]
Bug
* [x] If somehow a player gets both tumbled and cubed on the same frame (very hard to do but technically possible, as I've seen it happen once to a charmy) they get frozen in place (I think this is only if a mighty hard tumbles you and you get cubed just as you bounce on the floor)

Suggestion(s)
* [x] Cube Rings (when you use hammer on a cubed enemy) drops team rings instead (we can include green versions of the rings to recolour in battlepass)
* [x] Make Saw's hitbox a bit wider and taller
* [x] Flycarrying a teammate should give you a minor boost in height (like an extra jump as you grab them) to make more use of the flycarry (a bit like this:
![Image](https://github.com/felixLumyni/battlepass/assets/22688328/dfe65ea2-efdc-496c-a69c-012c9cd97891)

* [x] Cube can pop out digging knuckles'
* [x] Cube can encase players in iframes
* [x] Laser increases priority based on distance
* ~~Cube melee spike hitbox on bottom spike-tumbles if they have 0 def (like inazuma spike)~~ EDIT: I tried it but the game seemed very confused on whether to damage the enemy, tumble them, or cube them (inconsistent combinations of all 3). ~lumyni
* [x] Instead of making Laser infinite with the flag, what if instead when you reached 0 ammo you used your rings instead (can't kill self)

(I will edit this if I think of any more)

**Comment by felixLumyni** [comment]
complete

[v1 download](https://cdn.discordapp.com/attachments/1177410102140084334/1263338441899511900/whisperpass-v1.pk3?ex=6699df1c&is=66988d9c&hm=c48635574fbb8652fc96c6222d21c73b66a98ad3e12bc45a725d2904e6d0d8e9&)

**Comment by felixLumyni** [comment]
added bugfix todo list

**Comment by felixLumyni** [comment]
> added bugfix todo list

completed
